### PR TITLE
Updates for review

### PR DESCRIPTION
**Pull request by bonzini**
Hi Liu Jiang, please merge this pull request so that we can hopefully commit this crate to rust-vmm!

### CODE REVIEW

**Comment by jiangliu** [comment]
Hi Paolo,
       The commit history seems a little messy now, my fault:(. So I plan to clean it up by folding simple bugfix commits into those introducing them. Do you prefer sending another PR with the cleaner commit history or force-pushing  to the current PR?

**Comment by jiangliu** [comment]
Hi Paolo,
      I have clean up the commit history a bit and push it to https://github.com/jiangliu/vm-memory/tree/v3 .
Please help to review it and I will send another PR for the new version if you are OK with it, 
Thanks!

**Comment by bonzini** [comment]
Yes, it's okay. I am even okay with squashing everything in one commit
though. Ask in the original pull request what they prefer.

Also, what about renaming DataInit to BytesValued?

Paolo

Il lun 25 mar 2019, 16:39 Jiang Liu <notifications@github.com> ha scritto:

**Comment by jiangliu** [comment]
Good idea to rename DataInit to BytesValued, and also propose to rename data_init.rs <http://data_init.rs/> to bytes.rs <http://bytes.rs/>.

**Pull request merged**
